require("entity.air-filter")
require("entity.boiler")
require("entity.chemical-plant")
require("entity.combustion-chamber")
require("entity.compressor")
require("entity.crusher")
require("entity.distillery")
require("entity.electrolyzer.electrolyzer")
require("entity.electrolyzer.item")
require("entity.flotation-cell")
require("entity.foundry")
require("entity.geothermal-plant.geothermal-build")
require("entity.geothermal-plant.geothermal-reactor")
require("entity.geothermal-plant.item")
require("entity.heat-exchanger")
require("entity.hydro-plant")
require("entity.nanofabricator")

-- require("entity.small-furnace")
require("entity.steam-turbine")
require("entity.stirling-engine")

if mods["lambent-nil"] then
	require("entity.vacuum-chamber")
end
