require("prototypes.entities.splitters")
require("prototypes.entities.transport-belts")
require("prototypes.entities.underground-belts")
require("prototypes.entities.construction-robots")
require("prototypes.entities.logistic-robots")
